### ISSUE TITLE
Win 11 22H2 Much Needed Updates

### ISSUE THREAD

**Issue by jgarybrooks** [manifestinteractive/weather-bar-app#47]
#### Overview:  This is a much needed tool in the business environment.  Everyone out there is using weather as an employee productivity rabbit hole with the hope of monetization.

This app as is (1.0.0) loads, starts and runs on Windows 11 Enterprise Version 22H2 and provides simple access to the weather.  It needs a couple of minor changes to be more effective.

#### Issues:  Font Color/ Contrast:  With the windows built in themes you cannot see the ICON or information on the tool bar.  You have to click the ICON to see the weather which is just another distraction,  To change the Toolbar Color to create readable contrast requires the MS Store (another rabbit hole) plus IT customization labor.  Providing at least basic font / Icon 
contrast options in "Preferences" would fix this.

"OpenWeatherMap" Link:  Another rabbit hole...  Publish the logo and the www.{DOMAIN} in copiable format so people can explore on their own.  However clicking through on the app is just another rabbit hole.  I spent an hour looking at the weather in England and the Continent and musing about why you were using a UK source (which works quite adequately). 

Minor:  Weather Window stays up when you click out of the pane.  You can elect to have it behind "Real Work".  However, this is abnormal windows behavior and causes one to focus back on the app to figure out how to close it.  Just another distraction.

Minor:  When first loaded Accessing "Preferences" by {Right-Clicking} the Icon the preferences page showed "Loading" forever.  This cleared up after accessing "Preferences" from the Window. 

#### Steps to Duplicate _( required for bug reports )_: 

Install on Windows 11 22H2

**Comment by Brier1104** [comment]
Is this widget still being supported?

**Comment by manifestinteractive** [comment]
This project works just fine for most folks. Even other Windows 11 users, you can see in other Windows 11 issues people state as such.  I've got two Windows 11 devices I use right now and they also work fine on there.

This is open source software. If it's not working for you, maybe contribute a fix instead of suggesting a project be archived because you're specific issue on you're specific device is not resolved. It's not like I charge for this app ;)

The reality is that it works fine for most people without any changes needed for years now. That's not a reason to archive a project. 

As I've stated, I am working on a Windows 11 fix in my spare time for the few that are impacted by it, but no, it's not a priority.  I do have a full time job y'all ;)
